apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-counter
  name: {{ .Release.Name }}-counter
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}-counter
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-counter
    spec:
      containers:
        - image: ondrejsika/counter
          name: {{ .Release.Name }}-counter
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: {{ .Release.Name }}-redis
