apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-counter
  name: {{ .Release.Name }}-counter
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    service: {{ .Release.Name }}-counter
