apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    service: {{ .Release.Name }}-redis
