apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: {{ .Release.Name }}-redis-data
  name: {{ .Release.Name }}-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
